### ISSUE TITLE
opendp 0.1.0 release

### ISSUE THREAD

**Issue by andrewvyrros** [opendp/opendp#210]
Outstanding tasks:

- [x] Put floating point mechanisms behind feature flag (partial implementation of #43)
- [x] Add Python README.md file (#217)
- [x] Limit Python gen during opendp-ffi build (#220)
- [x] Python local install (#200)

**Comment by andrewvyrros** [comment]
Remaining tasks:

* Feature flag for enabling floating point mechanism
* Python README.md file
* Fix default features for opendp-ffi build

**Comment by andrewvyrros** [comment]
https://github.com/opendp/opendp/releases/tag/v0.1.0
